# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# If not configured otherwise, only run on commits
default_stages:
  - commit
repos:
  - repo: https://github.com/fluxninja/pre-commit-golang
    rev: v1.0.0-fn
    hooks:
      - id: go-mod-tidy
        args:
          - -compat=1.19
  # local hooks
  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        entry: ./scripts/golangci_lint.sh
        language: script
        pass_filenames: false
        require_serial: false
        types:
          - go
        stages:
          - commit
        args:
          - --fix
