version: 2.1

# this allows to use CircleCI's dynamic configuration feature
setup: true

executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2021.07


orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  version: 2
  filter-paths-main:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - not:
            matches:
              &is_not_empty_tag {
                value: << pipeline.git.tag >>,
                pattern: "^.+$",
              }
    jobs:
      - path-filtering/filter: &path_filtering_job
          base-revision: << pipeline.git.base_revision >>
          config-path: .circleci/continue-workflows.yml
          mapping: |
            .* updated-aperture-go true
  filter-paths-pr:
    when:
      and:
        - not:
            equal: [main, << pipeline.git.branch >>]
        - not:
            matches: *is_not_empty_tag
    jobs:
      - path-filtering/filter:
          <<: *path_filtering_job
          base-revision: main
