// Code generated by "enumer -type=Code -output=code-string.go"; DO NOT EDIT.

package aperture

import (
	"fmt"
	"strings"
)

const _CodeName = "OkError"

var _CodeIndex = [...]uint8{0, 2, 7}

const _CodeLowerName = "okerror"

func (i Code) String() string {
	if i >= Code(len(_CodeIndex)-1) {
		return fmt.Sprintf("Code(%d)", i)
	}
	return _CodeName[_CodeIndex[i]:_CodeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CodeNoOp() {
	var x [1]struct{}
	_ = x[Ok-(0)]
	_ = x[Error-(1)]
}

var _CodeValues = []Code{Ok, Error}

var _CodeNameToValueMap = map[string]Code{
	_CodeName[0:2]:      Ok,
	_CodeLowerName[0:2]: Ok,
	_CodeName[2:7]:      Error,
	_CodeLowerName[2:7]: Error,
}

var _CodeNames = []string{
	_CodeName[0:2],
	_CodeName[2:7],
}

// CodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CodeString(s string) (Code, error) {
	if val, ok := _CodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Code values", s)
}

// CodeValues returns all values of the enum
func CodeValues() []Code {
	return _CodeValues
}

// CodeStrings returns a slice of all String values of the enum
func CodeStrings() []string {
	strs := make([]string, len(_CodeNames))
	copy(strs, _CodeNames)
	return strs
}

// IsACode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Code) IsACode() bool {
	for _, v := range _CodeValues {
		if i == v {
			return true
		}
	}
	return false
}
